version: '2'

volumes:
  gems:
    driver: local

services:

  engine:
    image: r-base:3.2.1
    volumes:
      - .:/app
    working_dir: /app
    command: Rscript start.R -- --bootstrap-packrat
    expose:
      - 6311

  client:
    image: ruby:2.2.3
    command: bundle console
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - gems:/usr/local/bundle
      - ./ejemplos/ruby-client:/usr/src/app
      - ./tmp/sample-data:/sample-data
    working_dir: /usr/src/app
    links:
      - engine
    environment:
      ENGINE_URL: tcp://engine:6311 # The URL pointing to our engine container
